spring.application.name=Book-Eum

# application.properties ??
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA ?? (??? ?? ?? ??)
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

# FastAPI ?? ??
analysis.fastapi.url=http://localhost:8000/analyze

# ?? EPUB ???? ??? ???? (?? ???)
analysis.local-epub-dir=/Users/luna/CAU/2025-2/Capston Design 1/epub

musicai.dummy.file-path=/Users/luna/CAU/2025-2/Capston Design 1/music/demo-music.mp3
storage.music.local-dir=/Users/luna/CAU/2025-2/Capston Design 1/music
storage.epub.local-dir=/Users/luna/CAU/2025-2/Capston Design 1/epub
