spring.application.name=Book-Eum

# application.properties ??

# DB
spring.datasource.url=jdbc:mysql://localhost:3306/Book_Eum?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=luna0514
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JPA
spring.jpa.hibernate.ddl-auto=update

# FastAPI
analysis.fastapi.url=http://localhost:8000/analyze

# ?? EPUB ???? ??? ???? (?? ???)
#analysis.local-epub-dir=/Users/luna/CAU/2025-2/Capston Design 1/epub
#musicai.dummy.file-path=/Users/luna/CAU/2025-2/Capston Design 1/music/demo-music.mp3
#storage.music.local-dir=/Users/luna/CAU/2025-2/Capston Design 1/music
#storage.epub.local-dir=/Users/luna/CAU/2025-2/Capston Design 1/epub

